version: '3'

services:
  db:
    restart: always
    image: postgres:10-alpine
    # user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - .dbdata:/var/lib/postgresql:rw
    environment:
      POSTGRES_DB: battletrack
      POSTGRES_USER: btuser
      POSTGRES_PASSWORD: btpassword

  backend:
    build: ./backend/
    image: registry.gitlab.com/lucaspickering/battletrack/backend
    command: ./manage.py runserver 0.0.0.0:8000
    user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - ./backend/:/battletrack:rw
    depends_on:
      - db
    environment:
      - BT_DEV_API_KEY
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend/
    image: registry.gitlab.com/lucaspickering/battletrack/frontend
    user: "${DOCKER_UID}:${DOCKER_GID}"
    command: npm start
    volumes:
      - ./frontend/:/battletrack:rw
    ports:
      - "3000:3000"
