version: '3'

services:
  db:
    restart: always
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: battletrack
      POSTGRES_USER: btuser
      POSTGRES_PASSWORD: btpassword

  backend:
    image: registry.gitlab.com/lucaspickering/battletrack/backend:${CI_COMMIT_REF_SLUG}
    command: sh -c "dockerize -wait tcp://db:5432 && ./manage.py test"
    depends_on:
      - db

  frontend:
    image: registry.gitlab.com/lucaspickering/battletrack/frontend:${CI_COMMIT_REF_SLUG}
    command: sh -c "yarn run lint && yarn run test"
    environment:
      CI: "true"
