version: '3'

services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=battletrack
      - POSTGRES_USER=btuser
      - POSTGRES_PASSWORD=btpassword

  backend:
    build: ./backend/
    image: registry.gitlab.com/lucaspickering/battletrack/backend
    command: sh -c "dockerize -wait tcp://db:5432 && ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/:/battletrack:rw
    depends_on:
      - db
    environment:
      - BT_DEV_API_KEY
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend/
    image: registry.gitlab.com/lucaspickering/battletrack/frontend
    command: yarn start
    volumes:
      - ./frontend/:/battletrack:rw
    ports:
      - "3000:3000"
