version: '3'

services:
  db:
    restart: always
    image: postgres:10-alpine
    volumes:
      - ./backend/.dbdata:/var/lib/postgresql:rw
    environment:
      POSTGRES_DB: battletrack
      POSTGRES_USER: btuser
      POSTGRES_PASSWORD: btpassword

  backend:
    build: ./backend/
    image: battletrack/backend
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/:/battletrack:rw
    depends_on:
      - db
    environment:
      - BT_DEV_API_KEY
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend/
    image: battletrack/frontend
    command: bash -c "npm start"
    volumes:
      - ./frontend/:/battletrack:rw
    ports:
      - "3000:3000"
