# Generated by Django 2.0.4 on 2018-04-24 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=75)),
                ('stack_count', models.PositiveSmallIntegerField()),
                ('category', models.CharField(max_length=20)),
                ('subcategory', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('shard', models.CharField(max_length=20)),
                ('mode', models.CharField(choices=[('solo', 'Solo'), ('duo', 'Duo'), ('squad', 'Squad')], max_length=10)),
                ('perspective', models.CharField(choices=[('tpp', 'TPP'), ('fpp', 'FPP')], max_length=10)),
                ('map_name', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('telemetry_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('shard', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=40)),
                ('player_name', models.CharField(max_length=30)),
                ('match_id', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RosterMatch',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('win_place', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=40)),
                ('vehicle_name', models.CharField(max_length=40)),
                ('health', models.FloatField()),
                ('fuel', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CarePackageEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='btcore.Event')),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='btcore.Position')),
            ],
            bases=('btcore.event',),
        ),
        migrations.CreateModel(
            name='GameStatePeriodicEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='btcore.Event')),
            ],
            bases=('btcore.event',),
        ),
        migrations.CreateModel(
            name='ItemEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='btcore.Event')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='btcore.Item')),
            ],
            bases=('btcore.event',),
        ),
        migrations.CreateModel(
            name='PlayerAttackEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='btcore.Event')),
                ('attack_type', models.CharField(max_length=20)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='btcore.Vehicle')),
                ('weapon', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='btcore.Item')),
            ],
            bases=('btcore.event',),
        ),
        migrations.CreateModel(
            name='PlayerEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='btcore.Event')),
                ('health', models.FloatField()),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='btcore.Position')),
            ],
            bases=('btcore.event',),
        ),
        migrations.CreateModel(
            name='PlayerKillEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='btcore.Event')),
                ('damage_type', models.CharField(max_length=40)),
                ('damage_causer', models.CharField(max_length=40)),
            ],
            bases=('btcore.event',),
        ),
        migrations.CreateModel(
            name='PlayerMatchStats',
            fields=[
                ('player_match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='btcore.PlayerMatch')),
                ('assists', models.PositiveSmallIntegerField()),
                ('boosts', models.PositiveSmallIntegerField()),
                ('damage_dealt', models.FloatField()),
                ('dbnos', models.PositiveSmallIntegerField()),
                ('death_type', models.CharField(max_length=20)),
                ('headshot_kills', models.PositiveSmallIntegerField()),
                ('heals', models.PositiveSmallIntegerField()),
                ('kill_place', models.PositiveSmallIntegerField()),
                ('kill_points', models.PositiveSmallIntegerField()),
                ('kill_streaks', models.PositiveSmallIntegerField()),
                ('kills', models.PositiveSmallIntegerField()),
                ('longest_kill', models.PositiveSmallIntegerField()),
                ('most_damage', models.PositiveSmallIntegerField()),
                ('revives', models.PositiveSmallIntegerField()),
                ('ride_distance', models.PositiveSmallIntegerField()),
                ('road_kills', models.PositiveSmallIntegerField()),
                ('team_kills', models.PositiveSmallIntegerField()),
                ('time_survived', models.PositiveSmallIntegerField()),
                ('vehicle_destroys', models.PositiveSmallIntegerField()),
                ('walk_distance', models.FloatField()),
                ('weapons_acquired', models.PositiveSmallIntegerField()),
                ('win_place', models.PositiveSmallIntegerField()),
                ('win_points', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTakeDamageEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='btcore.Event')),
                ('damage', models.FloatField()),
                ('damage_type', models.CharField(max_length=40)),
                ('damage_reason', models.CharField(max_length=40)),
                ('damage_causer', models.CharField(max_length=40)),
            ],
            bases=('btcore.event',),
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='btcore.Match')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='btcore.Event')),
            ],
            bases=('btcore.event',),
        ),
        migrations.AddField(
            model_name='rostermatch',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='btcore.Match'),
        ),
        migrations.AddField(
            model_name='playermatch',
            name='player_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='btcore.Player'),
        ),
        migrations.AddField(
            model_name='playermatch',
            name='roster_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='btcore.RosterMatch'),
        ),
        migrations.AddField(
            model_name='circle',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='btcore.Position'),
        ),
        migrations.CreateModel(
            name='VehicleDestroyEvent',
            fields=[
                ('vehicleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='btcore.VehicleEvent')),
            ],
            bases=('btcore.vehicleevent',),
        ),
        migrations.AddField(
            model_name='vehicleevent',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btcore.PlayerMatch'),
        ),
        migrations.AddField(
            model_name='vehicleevent',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='btcore.Vehicle'),
        ),
        migrations.AddField(
            model_name='playertakedamageevent',
            name='attacker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='btcore.PlayerMatch'),
        ),
        migrations.AlterUniqueTogether(
            name='playermatch',
            unique_together={('player_id', 'match_id')},
        ),
        migrations.AddField(
            model_name='playerkillevent',
            name='attacker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='btcore.PlayerMatch'),
        ),
        migrations.AddField(
            model_name='itemevent',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btcore.PlayerMatch'),
        ),
        migrations.AddField(
            model_name='itemevent',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='btcore.Position'),
        ),
        migrations.AddField(
            model_name='gamestateperiodicevent',
            name='blue_zone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='blue_event', to='btcore.Circle'),
        ),
        migrations.AddField(
            model_name='gamestateperiodicevent',
            name='red_zone',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_event', to='btcore.Circle'),
        ),
        migrations.AddField(
            model_name='gamestateperiodicevent',
            name='white_zone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='white_event', to='btcore.Circle'),
        ),
        migrations.AddField(
            model_name='event',
            name='telemetry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btcore.Telemetry'),
        ),
        migrations.AddField(
            model_name='vehicledestroyevent',
            name='attacker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='btcore.PlayerMatch'),
        ),
    ]
