# Generated by Django 2.0.6 on 2018-06-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='custom_match',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='swim_distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='map_name',
            field=models.CharField(choices=[('Erangel_Main', 'Erangel_Main'), ('Desert_Main', 'Desert_Main'), ('Savage_Main', 'Savage_Main')], max_length=50),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='longest_kill',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='time_survived',
            field=models.FloatField(),
        ),
    ]
