# Generated by Django 2.0.5 on 2018-05-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='mode',
            field=models.CharField(max_length=10),
        ),
    ]
