# Generated by Django 2.0.7 on 2018-08-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcore', '0002_auto_20180626_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='mode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='perspective',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
