# Generated by Django 2.0.4 on 2018-05-06 23:32

from django.db import migrations, models
import django.db.models.deletion
import telemetry.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('btcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='btcore.Match')),
            ],
        ),
        migrations.CreateModel(
            name='CarePackageEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telemetry.Event')),
                ('position', telemetry.fields.PositionField(max_length=64)),
            ],
            bases=('telemetry.event',),
        ),
        migrations.CreateModel(
            name='GameStatePeriodicEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telemetry.Event')),
                ('red_zone', telemetry.fields.CircleField(max_length=85)),
                ('white_zone', telemetry.fields.CircleField(max_length=85)),
                ('blue_zone', telemetry.fields.CircleField(max_length=85)),
            ],
            bases=('telemetry.event',),
        ),
        migrations.CreateModel(
            name='PlayerEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telemetry.Event')),
                ('player', telemetry.fields.EventPlayerField(max_length=64)),
            ],
            bases=('telemetry.event',),
        ),
        migrations.AddField(
            model_name='event',
            name='telemetry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='telemetry.Telemetry'),
        ),
        migrations.CreateModel(
            name='ItemEvent',
            fields=[
                ('playerevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telemetry.PlayerEvent')),
                ('item', telemetry.fields.ItemField(max_length=100)),
            ],
            bases=('telemetry.playerevent',),
        ),
        migrations.CreateModel(
            name='PlayerAttackEvent',
            fields=[
                ('playerevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telemetry.PlayerEvent')),
                ('attack_type', models.CharField(max_length=20)),
                ('weapon', telemetry.fields.ItemField(max_length=100)),
                ('vehicle', telemetry.fields.VehicleField(max_length=80)),
            ],
            bases=('telemetry.playerevent',),
        ),
        migrations.CreateModel(
            name='PlayerVictimEvent',
            fields=[
                ('playerevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telemetry.PlayerEvent')),
                ('attacker', telemetry.fields.EventPlayerField(max_length=64)),
                ('damage_type', models.CharField(max_length=40)),
                ('damage_causer', models.CharField(max_length=40)),
            ],
            bases=('telemetry.playerevent',),
        ),
        migrations.CreateModel(
            name='VehicleEvent',
            fields=[
                ('playerevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telemetry.PlayerEvent')),
                ('vehicle', telemetry.fields.VehicleField(max_length=80)),
            ],
            bases=('telemetry.playerevent',),
        ),
        migrations.CreateModel(
            name='ItemAttachEvent',
            fields=[
                ('itemevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telemetry.ItemEvent')),
                ('child_item', telemetry.fields.ItemField(max_length=100)),
            ],
            bases=('telemetry.itemevent',),
        ),
        migrations.CreateModel(
            name='PlayerTakeDamageEvent',
            fields=[
                ('playervictimevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telemetry.PlayerVictimEvent')),
                ('damage', models.FloatField()),
                ('damage_reason', models.CharField(max_length=40)),
            ],
            bases=('telemetry.playervictimevent',),
        ),
        migrations.CreateModel(
            name='VehicleDestroyEvent',
            fields=[
                ('vehicleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telemetry.VehicleEvent')),
                ('attacker', telemetry.fields.EventPlayerField(max_length=64)),
            ],
            bases=('telemetry.vehicleevent',),
        ),
    ]
