# Generated by Django 2.0.4 on 2018-05-09 04:18

from django.db import migrations, models
import django.db.models.deletion
import telemetry.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('btcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePackageEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('time', models.FloatField()),
                ('pos', telemetry.fields.PositionField(max_length=62)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameStatePeriodicEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('time', models.FloatField()),
                ('red_zone', telemetry.fields.CircleField(max_length=83)),
                ('white_zone', telemetry.fields.CircleField(max_length=83)),
                ('blue_zone', telemetry.fields.CircleField(max_length=83)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemAttachEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('time', models.FloatField()),
                ('player', telemetry.fields.EventPlayerField(max_length=145)),
                ('item', telemetry.fields.ItemField(max_length=100)),
                ('child_item', telemetry.fields.ItemField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('time', models.FloatField()),
                ('player', telemetry.fields.EventPlayerField(max_length=145)),
                ('item', telemetry.fields.ItemField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerAttackEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('time', models.FloatField()),
                ('player', telemetry.fields.EventPlayerField(max_length=145)),
                ('attack_type', models.CharField(max_length=20)),
                ('weapon', telemetry.fields.ItemField(max_length=100)),
                ('vehicle', telemetry.fields.VehicleField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerKillEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('time', models.FloatField()),
                ('player', telemetry.fields.EventPlayerField(max_length=145)),
                ('attacker', telemetry.fields.EventPlayerField(max_length=145)),
                ('damage_type', models.CharField(max_length=40)),
                ('damage_causer', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerPositionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('time', models.FloatField()),
                ('player', telemetry.fields.EventPlayerField(max_length=145)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerTakeDamageEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('time', models.FloatField()),
                ('player', telemetry.fields.EventPlayerField(max_length=145)),
                ('attacker', telemetry.fields.EventPlayerField(max_length=145)),
                ('damage_type', models.CharField(max_length=40)),
                ('damage_causer', models.CharField(max_length=40)),
                ('damage', models.FloatField()),
                ('damage_reason', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='btcore.Match')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDestroyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('time', models.FloatField()),
                ('player', telemetry.fields.EventPlayerField(max_length=145)),
                ('vehicle', telemetry.fields.VehicleField(max_length=100)),
                ('attacker', telemetry.fields.EventPlayerField(max_length=145)),
                ('telemetry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_vehicledestroyevents', to='telemetry.Telemetry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('time', models.FloatField()),
                ('player', telemetry.fields.EventPlayerField(max_length=145)),
                ('vehicle', telemetry.fields.VehicleField(max_length=100)),
                ('telemetry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_vehicleevents', to='telemetry.Telemetry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='playertakedamageevent',
            name='telemetry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_playertakedamageevents', to='telemetry.Telemetry'),
        ),
        migrations.AddField(
            model_name='playerpositionevent',
            name='telemetry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_playerpositionevents', to='telemetry.Telemetry'),
        ),
        migrations.AddField(
            model_name='playerkillevent',
            name='telemetry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_playerkillevents', to='telemetry.Telemetry'),
        ),
        migrations.AddField(
            model_name='playerattackevent',
            name='telemetry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_playerattackevents', to='telemetry.Telemetry'),
        ),
        migrations.AddField(
            model_name='itemevent',
            name='telemetry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_itemevents', to='telemetry.Telemetry'),
        ),
        migrations.AddField(
            model_name='itemattachevent',
            name='telemetry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_itemattachevents', to='telemetry.Telemetry'),
        ),
        migrations.AddField(
            model_name='gamestateperiodicevent',
            name='telemetry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_gamestateperiodicevents', to='telemetry.Telemetry'),
        ),
        migrations.AddField(
            model_name='carepackageevent',
            name='telemetry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_carepackageevents', to='telemetry.Telemetry'),
        ),
    ]
