# Generated by Django 2.0.4 on 2018-05-05 03:34

from django.db import migrations, models
import django.db.models.deletion
import telemetry.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('btcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=75)),
                ('stack_count', models.PositiveSmallIntegerField()),
                ('category', models.CharField(max_length=20)),
                ('subcategory', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='btcore.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=40)),
                ('vehicle_name', models.CharField(max_length=40)),
                ('health', models.FloatField()),
                ('fuel', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CarePackageEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telemetry.Event')),
                ('position', telemetry.fields.PositionField(max_length=64)),
            ],
            bases=('telemetry.event',),
        ),
        migrations.CreateModel(
            name='GameStatePeriodicEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telemetry.Event')),
                ('red_zone', telemetry.fields.CircleField(blank=True, max_length=85)),
                ('white_zone', telemetry.fields.CircleField(blank=True, max_length=85)),
                ('blue_zone', telemetry.fields.CircleField(max_length=85)),
            ],
            bases=('telemetry.event',),
        ),
        migrations.CreateModel(
            name='ItemEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telemetry.Event')),
                ('position', telemetry.fields.PositionField(max_length=64)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='telemetry.Item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btcore.PlayerMatch')),
            ],
            bases=('telemetry.event',),
        ),
        migrations.CreateModel(
            name='PlayerEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telemetry.Event')),
                ('position', telemetry.fields.PositionField(max_length=64)),
                ('health', models.FloatField()),
            ],
            bases=('telemetry.event',),
        ),
        migrations.CreateModel(
            name='VehicleEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telemetry.Event')),
            ],
            bases=('telemetry.event',),
        ),
        migrations.AddField(
            model_name='event',
            name='telemetry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='telemetry.Telemetry'),
        ),
        migrations.CreateModel(
            name='PlayerAttackEvent',
            fields=[
                ('playerevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telemetry.PlayerEvent')),
                ('attack_type', models.CharField(max_length=20)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='telemetry.Vehicle')),
                ('weapon', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='telemetry.Item')),
            ],
            bases=('telemetry.playerevent',),
        ),
        migrations.CreateModel(
            name='PlayerKillEvent',
            fields=[
                ('playerevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telemetry.PlayerEvent')),
                ('damage_type', models.CharField(max_length=40)),
                ('damage_causer', models.CharField(max_length=40)),
                ('attacker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='btcore.PlayerMatch')),
            ],
            bases=('telemetry.playerevent',),
        ),
        migrations.CreateModel(
            name='PlayerTakeDamageEvent',
            fields=[
                ('playerevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telemetry.PlayerEvent')),
                ('damage', models.FloatField()),
                ('damage_type', models.CharField(max_length=40)),
                ('damage_reason', models.CharField(max_length=40)),
                ('damage_causer', models.CharField(max_length=40)),
                ('attacker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='btcore.PlayerMatch')),
            ],
            bases=('telemetry.playerevent',),
        ),
        migrations.CreateModel(
            name='VehicleDestroyEvent',
            fields=[
                ('vehicleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telemetry.VehicleEvent')),
                ('attacker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='btcore.PlayerMatch')),
            ],
            bases=('telemetry.vehicleevent',),
        ),
        migrations.AddField(
            model_name='vehicleevent',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btcore.PlayerMatch'),
        ),
        migrations.AddField(
            model_name='vehicleevent',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='telemetry.Vehicle'),
        ),
        migrations.AddField(
            model_name='playerevent',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btcore.PlayerMatch'),
        ),
    ]
