# Generated by Django 2.0.6 on 2018-06-26 17:57

from django.db import migrations, models
import django.db.models.deletion
import telemetry.fields


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorDestroyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('time', models.FloatField()),
                ('player', telemetry.fields.EventPlayerField()),
                ('attacker', telemetry.fields.EventPlayerField(blank=True)),
                ('damage_type', models.CharField(max_length=40)),
                ('damage_reason', models.CharField(max_length=40)),
                ('damage_causer', models.CharField(max_length=40)),
                ('distance', models.FloatField()),
                ('item', telemetry.fields.ItemField()),
                ('telemetry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armordestroyevents', to='telemetry.Telemetry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerMakeGroggyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('time', models.FloatField()),
                ('player', telemetry.fields.EventPlayerField()),
                ('attacker', telemetry.fields.EventPlayerField(blank=True)),
                ('damage_type', models.CharField(max_length=40)),
                ('damage_reason', models.CharField(max_length=40)),
                ('damage_causer', models.CharField(max_length=40)),
                ('distance', models.FloatField()),
                ('telemetry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playermakegroggyevents', to='telemetry.Telemetry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SwimEndEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('time', models.FloatField()),
                ('player', telemetry.fields.EventPlayerField()),
                ('swim_distance', models.FloatField()),
                ('telemetry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimendevents', to='telemetry.Telemetry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleLeaveEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('time', models.FloatField()),
                ('player', telemetry.fields.EventPlayerField()),
                ('vehicle', telemetry.fields.VehicleField()),
                ('seat_index', models.PositiveSmallIntegerField()),
                ('ride_distance', models.FloatField()),
                ('telemetry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleleaveevents', to='telemetry.Telemetry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleRideEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('time', models.FloatField()),
                ('player', telemetry.fields.EventPlayerField()),
                ('vehicle', telemetry.fields.VehicleField()),
                ('seat_index', models.PositiveSmallIntegerField()),
                ('telemetry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiclerideevents', to='telemetry.Telemetry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='vehicleevent',
            name='telemetry',
        ),
        migrations.AddField(
            model_name='playerkillevent',
            name='damage_reason',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerkillevent',
            name='distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VehicleEvent',
        ),
    ]
